baseurl: "https://example.org/"
title: "Conference name"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Conference name"
  Description: "Conference description"
  Date: "November 15"
  Price: "Only $100" # If your event is free, just comment this line
  Venue: "Coco Bongo"
  Address: "Boulevard Kukulcan, 30"
  City:  "Cancún"
  State: "Quintana"
  City:  "Mexico"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - organization
    - sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    organization: "Organization"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"
    steering: "Steering Committee"
    chair: "Program Chairs"
    tpc: "Technical Program Committee"
    
  Subtitles:
    about: "ACNS is an annual conference focusing on current developments that advance the areas of applied cryptography, cyber security (including network and computer security) and privacy. The goal is to represent both academic research works as well as developments in industrial and technical frontiers."

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Steering Committee
  Steering:
    - name: "Hugo"
      affiliation: "Hugo University, Universe"
      url: "http://gohugo.io"

  # List of Program Chair(s)
  Chair:
    - name: "Hugo"
      affiliation: "Hugo University, Universe"
      url: "http://gohugo.io"

  # List of TPC
  TPC:
    - name: "Hugo"
      affiliation: "Hugo University, Universe"
      url: "http://gohugo.io"
    - name: "Hugo"
      affiliation: "Hugo University, Universe"
      url: "http://gohugo.io"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - session: "Check-in / Breakfast"
      time: "9h00"
      chair: "H. Ugo"
    - session: "Session 1: How-To Hugo"
      time: "10h00"
      chair: "H. Ugo"
      presentations:
        - title: "title 1"
          author: "Author 1"
          pdf: ""
          slides: ""
        - title: "title 2"
          author: "Author 2"
          pdf: ""
          slides: ""